/*
 * Autogenerated file.
 * Do not touch
 * Willy
 */

export const elixirSnippet = `[35mdefmodule[0m [33mHelloWeb[0m.[33mProductController[0m [35mdo[0m
  [35muse[0m [33mHelloWeb[0m, [32m:[0m[32mcontroller[0m

  [35malias[0m [33mHello[0m.[33mCatalog[0m
  [35malias[0m [33mHello[0m.[33mCatalog[0m.[33mProduct[0m

[32m  [0m[32m#[0m[32m list all products[0m
  [35mdef[0m [34mindex[0m(conn, _params) [35mdo[0m
    products [35m=[0m [33mCatalog[0m.list_products()
    render(conn, [32m:[0m[32mindex[0m, [33mproducts[0m[33m:[0m products)
  [35mend[0m

  [35mdef[0m [34mnew[0m(conn, _params) [35mdo[0m
    changeset [35m=[0m [33mCatalog[0m.change_product(%[33mProduct[0m{})
    render(conn, [32m:[0m[32mnew[0m, [33mchangeset[0m[33m:[0m changeset)
  [35mend[0m

  [35mdef[0m [34mcreate[0m(conn, %{[32m"[0m[32mproduct[0m[32m"[0m [35m=>[0m product_params}) [35mdo[0m
    [35mcase[0m [33mCatalog[0m.create_product(product_params) [35mdo[0m
      {[32m:[0m[32mok[0m, product} [35m->[0m
        conn
        [35m|>[0m put_flash([32m:[0m[32minfo[0m, [32m"[0m[32mProduct created successfully.[0m[32m"[0m)
        [35m|>[0m redirect([33mto[0m[33m:[0m [35m~p[0m[32m"[0m[32m/products/[0m[32m#{[0mproduct}[32m"[0m)

      {[32m:[0m[32merror[0m, %[33mEcto[0m.[33mChangeset[0m{} [35m=[0m changeset} [35m->[0m
        render(conn, [32m:[0m[32mnew[0m, [33mchangeset[0m[33m:[0m changeset)
    [35mend[0m
  [35mend[0m

  [35mdef[0m [34mshow[0m(conn, %{[32m"[0m[32mid[0m[32m"[0m [35m=>[0m id}) [35mdo[0m
    product [35m=[0m [33mCatalog[0m.get_product!(id)
    render(conn, [32m:[0m[32mshow[0m, [33mproduct[0m[33m:[0m product)
  [35mend[0m
[35mend[0m
`;

export const pythonSnippet = `[35mfrom[0m flask [35mimport[0m Flask

app [35m=[0m Flask(__name__)

[32m#[0m[32m just a dummy route[0m
@app.route([32m"[0m[32m/[0m[32m"[0m)
[35mdef[0m [34mhello_world[0m():
    [35mreturn[0m [32m"[0m[32m<p>Hello, World!</p>[0m[32m"[0m

@app.route([32m"[0m[32m/me[0m[32m"[0m)
[35mdef[0m [34mme_api[0m():
    user [35m=[0m get_current_user()
    [35mreturn[0m {
        [32m"[0m[32musername[0m[32m"[0m: user.username,
        [32m"[0m[32mtheme[0m[32m"[0m: user.theme,
        [32m"[0m[32mimage[0m[32m"[0m: url_for([32m"[0m[32muser_image[0m[32m"[0m, filename[35m=[0muser.image),
    }

@app.route([32m"[0m[32m/users[0m[32m"[0m)
[35mdef[0m [34musers_api[0m():
    users [35m=[0m get_all_users()
    [35mreturn[0m [user.to_json() [35mfor[0m user [35min[0m users]
`;

export const typescriptSnippet = `[35mimport[0m express, { Express, Request, Response } [35mfrom[0m [32m"[0m[32mexpress[0m[32m"[0m;

[35mconst[0m app[35m:[0m Express [35m=[0m [34mexpress[0m();
[35mconst[0m port [35m=[0m process.env.PORT [35m||[0m [33m3000[0m;

app.[36mget[0m([32m"[0m[32m/[0m[32m"[0m, (_req[35m:[0m Request, res[35m:[0m Response) [35m=>[0m {
  res.[36msend[0m([32m"[0m[32mHello, World![0m[32m"[0m);
});

[32m//[0m[32m start the server[0m
app.[34mlisten[0m(port, () [35m=>[0m {
  [33mconsole[0m.[36mlog[0m([32m"[0m[32m[server]: Server is running at http://localhost:[0m[32m"[0m [35m+[0m port);
});
`;
