/*
 * Autogenerated file.
 * Do not touch
 * Willy
 */

export const elixirSnippet = `[35mdefmodule[0m [33mHelloWeb[0m.[33mProductController[0m [35mdo[0m
  [35muse[0m [33mHelloWeb[0m, [32m:[0m[32mcontroller[0m

  [35malias[0m [33mHello[0m.[33mCatalog[0m
  [35malias[0m [33mHello[0m.[33mCatalog[0m.[33mProduct[0m

[32m  [0m[32m#[0m[32m list all products[0m
  [35mdef[0m [34mindex[0m(conn, _params) [35mdo[0m
    products [35m=[0m [33mCatalog[0m.list_products()
    render(conn, [32m:[0m[32mindex[0m, [33mproducts[0m[33m:[0m products)
  [35mend[0m

  [35mdef[0m [34mnew[0m(conn, _params) [35mdo[0m
    changeset [35m=[0m [33mCatalog[0m.change_product(%[33mProduct[0m{})
    render(conn, [32m:[0m[32mnew[0m, [33mchangeset[0m[33m:[0m changeset)
  [35mend[0m

  [35mdef[0m [34mcreate[0m(conn, %{[32m"[0m[32mproduct[0m[32m"[0m [35m=>[0m product_params}) [35mdo[0m
    [35mcase[0m [33mCatalog[0m.create_product(product_params) [35mdo[0m
      {[32m:[0m[32mok[0m, product} [35m->[0m
        conn
        [35m|>[0m put_flash([32m:[0m[32minfo[0m, [32m"[0m[32mProduct created successfully.[0m[32m"[0m)
        [35m|>[0m redirect([33mto[0m[33m:[0m [35m~p[0m[32m"[0m[32m/products/[0m[32m#{[0mproduct}[32m"[0m)

      {[32m:[0m[32merror[0m, %[33mEcto[0m.[33mChangeset[0m{} [35m=[0m changeset} [35m->[0m
        render(conn, [32m:[0m[32mnew[0m, [33mchangeset[0m[33m:[0m changeset)
    [35mend[0m
  [35mend[0m

  [35mdef[0m [34mshow[0m(conn, %{[32m"[0m[32mid[0m[32m"[0m [35m=>[0m id}) [35mdo[0m
    product [35m=[0m [33mCatalog[0m.get_product!(id)
    render(conn, [32m:[0m[32mshow[0m, [33mproduct[0m[33m:[0m product)
  [35mend[0m
[35mend[0m
`;

export const pythonSnippet = `[35mfrom[0m flask [35mimport[0m Flask

app [35m=[0m Flask(__name__)

[32m#[0m[32m just a dummy route[0m
@app.route([32m"[0m[32m/[0m[32m"[0m)
[35mdef[0m [34mhello_world[0m():
    [35mreturn[0m [32m"[0m[32m<p>Hello, World!</p>[0m[32m"[0m

@app.route([32m"[0m[32m/me[0m[32m"[0m)
[35mdef[0m [34mme_api[0m():
    user [35m=[0m get_current_user()
    [35mreturn[0m {
        [32m"[0m[32musername[0m[32m"[0m: user.username,
        [32m"[0m[32mtheme[0m[32m"[0m: user.theme,
        [32m"[0m[32mimage[0m[32m"[0m: url_for([32m"[0m[32muser_image[0m[32m"[0m, filename[35m=[0muser.image),
    }

@app.route([32m"[0m[32m/users[0m[32m"[0m)
[35mdef[0m [34musers_api[0m():
    users [35m=[0m get_all_users()
    [35mreturn[0m [user.to_json() [35mfor[0m user [35min[0m users]
`;

export const typescriptSnippet = `[35mimport[0m express, { Express, Request, Response } [35mfrom[0m [32m"[0m[32mexpress[0m[32m"[0m;

[35mconst[0m app[35m:[0m Express [35m=[0m [34mexpress[0m();
[35mconst[0m port [35m=[0m process.env.PORT [35m||[0m [33m3000[0m;

app.[36mget[0m([32m"[0m[32m/[0m[32m"[0m, (_req[35m:[0m Request, res[35m:[0m Response) [35m=>[0m {
  res.[36msend[0m([32m"[0m[32mHello, World![0m[32m"[0m);
});

[32m//[0m[32m start the server[0m
app.[34mlisten[0m(port, () [35m=>[0m {
  [33mconsole[0m.[36mlog[0m([32m"[0m[32m[server]: Server is running at http://localhost:[0m[32m"[0m [35m+[0m port);
});
`;

export const vitestSnippet = `
[7m[1m[36m RUN [39m[22m[27m [36mv1.5.0[39m [90m/home/ham/dev/root-loops/snippets[39m

 [32m✓[39m test.js[2m > [22mroot loops color generator[2m > [22mpours milk into the bowl
 [32m✓[39m test.js[2m > [22mroot loops color generator[2m > [22madds unhealthy amounts of sugar
 [32m✓[39m test.js[2m > [22mroot loops color generator[2m > [22mincludes worrying amounts of artificial flavours
 [32m✓[39m test.js[2m > [22mroot loops color generator[2m > [22mlets the bowl sit for maximum sogginess
 [31m×[39m test.js[2m > [22mroot loops color generator[2m > [22madds fresh fruit
[31m   → expected true to be false // Object.is equality[39m

[2m Test Files [22m [1m[31m1 failed[39m[22m[90m (1)[39m
[2m      Tests [22m [1m[31m1 failed[39m[22m[2m | [22m[1m[32m4 passed[39m[22m[2m | [22m[90m1 todo[39m[90m (6)[39m
[2m   Start at [22m 17:22:51
[2m   Duration [22m 239ms[2m (transform 18ms, setup 0ms, collect 9ms, tests 8ms, environment 0ms, prepare 54ms)[22m


[31m⎯⎯⎯⎯⎯⎯⎯[1m[7m Failed Tests 1 [27m[22m⎯⎯⎯⎯⎯⎯⎯[39m

[31m[1m[7m FAIL [27m[22m[39m test.js[2m > [22mroot loops color generator[2m > [22madds fresh fruit
[31m[1mAssertionError[22m: expected true to be false // Object.is equality[39m

- Expected
+ Received

- false
+ true

[36m [2m❯[22m test.js:[2m21:18[22m[39m
    [90m 19| [39m
    [90m 20| [39m  [34mit[39m([32m"adds fresh fruit"[39m[33m,[39m () [33m=>[39m {
    [90m 21| [39m    [34mexpect[39m([35mtrue[39m)[33m.[39m[34mtoBe[39m([35mfalse[39m)[33m;[39m
    [90m   | [39m                 [31m^[39m
    [90m 22| [39m  })[33m;[39m
    [90m 23| [39m

[31m[2m⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯[22m[39m

`;

export const screenfetchSnippet = `[0m[32m                               [0m
[0m[32m                 -/+:.         [0m[1;34m ham[0m[1m@[0m[0m[1;34mhambook-2[0m
[0m[32m                :++++.         [0m[1;34m OS:[0m Ubuntu 24.04 noble[0m
[0m[32m               /+++/.          [0m[1;34m Kernel:[0m x86_64 Linux 6.8.0-31-generic[0m
[0m[32m       .:-::- .+/:-\`\`.::-      [0m[1;34m Uptime:[0m 10d 3h 25m[0m
[0m[32m    .:/++++++/::::/++++++/:\`   [0m[1;34m Packages:[0m 2664[0m
[0m[33m  .:///////////////////////:\`  [0m[1;34m Shell:[0m node[0m
[0m[33m  ////////////////////////\`    [0m[1;34m Resolution:[0m 5142x3840[0m
[0m[1;31m -+++++++++++++++++++++++\`     [0m[1;34m DE:[0m GNOME 46.0.1[0m
[0m[1;31m /++++++++++++++++++++++/      [0m[1;34m WM:[0m Mutter[0m
[0m[31m /sssssssssssssssssssssss.     [0m[1;34m WM Theme:[0m Adwaita[0m
[0m[31m :ssssssssssssssssssssssss-    [0m[1;34m GTK Theme:[0m Yaru-red-dark [GTK2/3][0m
[0m[35m  osssssssssssssssssssssssso/\` [0m[1;34m Icon Theme:[0m Yaru-red[0m
[0m[35m  \`syyyyyyyyyyyyyyyyyyyyyyyy+\` [0m[1;34m Font:[0m Ubuntu 11[0m
[0m[34m   \`ossssssssssssssssssssss/   [0m[1;34m Disk:[0m 385G / 469G (87%)[0m
[0m[34m     :ooooooooooooooooooo+.    [0m[1;34m CPU:[0m Intel Core i7-1065G7 @ 8x 3.9GHz [62.0°C][0m
[0m[34m      \`:+oo+/:-..-:/+o+/-      [0m[1;34m GPU:[0m Intel Corporation Iris Plus Graphics G7 (rev 07)[0m
[0m[34m                               [0m[1;34m RAM:[0m 10923MiB / 15573MiB[0m
`;
