import { toQueryString, type Recipe } from "$lib/ingredients";
import { type Cereals } from "$lib/cereals";
import { prepare } from "$lib/cereals";
import { textmateSyntaxRules } from "./textmate";

export function toVSCode(recipe: Recipe): string {
  const cereals = prepare(recipe);
  const queryString = toQueryString(recipe);

  const colors = {
    "workbench.colorCustomizations": {
      ...VSCodeUI(cereals),
      ...VSCodeTerminal(cereals),
    },
    "editor.tokenColorCustomizations": {
      textMateRules: textmateSyntaxRules(cereals),
    },
  };
  const config = JSON.stringify(colors, null, 2);

  return `
// Add the following config to your ~/.config/Code/Usersettings.json file.
// Root Loops: https://rootloops.sh?${queryString}
//
// NOTE: This will override other UI and syntax highlighting colors you
//       might expect to apply from extensions you installed. To use a
//       different color scheme installed via extensions, remove the config
//       below again.

${config}
  `;
}

function VSCodeTerminal(cereals: Cereals) {
  return {
    "terminal.ansiBlack": cereals.black.color_hex,
    "terminal.ansiBlue": cereals.blue.color_hex,
    "terminal.ansiBrightBlack": cereals.brightBlack.color_hex,
    "terminal.ansiBrightBlue": cereals.brightBlue.color_hex,
    "terminal.ansiBrightCyan": cereals.brightCyan.color_hex,
    "terminal.ansiBrightGreen": cereals.brightGreen.color_hex,
    "terminal.ansiBrightMagenta": cereals.brightMagenta.color_hex,
    "terminal.ansiBrightRed": cereals.brightRed.color_hex,
    "terminal.ansiBrightWhite": cereals.brightWhite.color_hex,
    "terminal.ansiBrightYellow": cereals.brightYellow.color_hex,
    "terminal.ansiCyan": cereals.cyan.color_hex,
    "terminal.ansiGreen": cereals.green.color_hex,
    "terminal.ansiMagenta": cereals.magenta.color_hex,
    "terminal.ansiRed": cereals.red.color_hex,
    "terminal.ansiWhite": cereals.white.color_hex,
    "terminal.ansiYellow": cereals.yellow.color_hex,
    "terminal.background": cereals.background.color_hex,
    "terminal.foreground": cereals.foreground.color_hex,
    "terminalCursor.foreground": cereals.white.color_hex,
  };
}

function VSCodeUI(cereals: Cereals): object {
  return {
    "activityBar.activeBackground": cereals.black.color_hex,
    "activityBar.activeBorder": cereals.red.color_hex,
    "activityBar.background": cereals.background.color_hex,
    "activityBar.border": cereals.black.color_hex,
    "activityBar.foreground": cereals.foreground.color_hex,
    "activityBar.inactiveForeground": cereals.white.color_hex,
    "activityBarBadge.background": cereals.cyan.color_hex,
    "activityBarBadge.foreground": cereals.background.color_hex,
    "badge.background": cereals.cyan.color_hex,
    "badge.foreground": cereals.background.color_hex,
    "banner.background": cereals.red.color_hex,
    "breadcrumb.activeSelectionForeground": cereals.red.color_hex,
    "breadcrumb.background": cereals.background.color_hex,
    "breadcrumb.focusForeground": cereals.cyan.color_hex,
    "breadcrumb.foreground": cereals.white.color_hex,
    "breadcrumbPicker.background": cereals.background.color_hex,
    "button.background": cereals.blue.color_hex,
    "button.foreground": cereals.background.color_hex,
    "button.hoverBackground": cereals.brightBlue.color_hex,
    "button.secondaryBackground": cereals.black.color_hex,
    "checkbox.background": cereals.background.color_hex,
    "checkbox.border": cereals.blue.color_hex,
    "checkbox.foreground": cereals.foreground.color_hex,
    "commandCenter.activeBackground": cereals.brightBlack.color_hex,
    "commandCenter.background": cereals.background.color_hex,
    "commandCenter.border": cereals.brightBlack.color_hex,
    "debugIcon.breakpointForeground": cereals.red.color_hex,
    descriptionForeground: cereals.brightWhite.color_hex,
    disabledForeground: cereals.white.color_hex,
    "dropdown.background": cereals.background.color_hex,
    "dropdown.listBackground": cereals.black.color_hex,
    "editor.background": cereals.background.color_hex,
    "editor.foreground": cereals.foreground.color_hex,
    "editor.lineHighlightBackground": cereals.black.color_hex,
    "editor.selectionBackground": cereals.brightBlack.color_hex,
    "editorCursor.foreground": cereals.brightWhite.color_hex,
    "editorGroup.border": cereals.brightBlack.color_hex,
    "editorGroup.emptyBackground": cereals.background.color_hex,
    "editorGroupHeader.noTabsBackground": cereals.background.color_hex,
    "editorGroupHeader.tabsBackground": cereals.background.color_hex,
    "editorGutter.addedBackground": cereals.green.color_hex,
    "editorGutter.deletedBackground": cereals.red.color_hex,
    "editorGutter.modifiedBackground": cereals.blue.color_hex,
    "editorHoverWidget.background": cereals.background.color_hex,
    "editorHoverWidget.border": cereals.brightBlack.color_hex,
    "editorHoverWidget.foreground": cereals.foreground.color_hex,
    "editorIndentGuide.activeBackground1": cereals.brightBlack.color_hex,
    "editorIndentGuide.background1": cereals.black.color_hex,
    "editorLineNumber.activeForeground": cereals.red.color_hex,
    "editorLineNumber.foreground": cereals.brightBlack.color_hex,
    "editorSuggestWidget.background": cereals.background.color_hex,
    "editorSuggestWidget.border": cereals.brightBlack.color_hex,
    "editorSuggestWidget.focusHighlightForeground": cereals.red.color_hex,
    "editorSuggestWidget.foreground": cereals.foreground.color_hex,
    "editorSuggestWidget.highlightForeground": cereals.red.color_hex,
    "editorSuggestWidget.selectedBackground": cereals.black.color_hex,
    "editorSuggestWidget.selectedForeground": cereals.foreground.color_hex,
    "editorSuggestWidget.selectedIconForeground": cereals.foreground.color_hex,
    "editorWidget.background": cereals.background.color_hex,
    "editorWidget.foreground": cereals.foreground.color_hex,
    "editorWidget.resizeBorder": cereals.brightBlack.color_hex,
    errorForeground: cereals.red.color_hex,
    focusBorder: cereals.white.color_hex,
    foreground: cereals.foreground.color_hex,
    "input.background": cereals.black.color_hex,
    "input.border": cereals.brightBlack.color_hex,
    "input.foreground": cereals.foreground.color_hex,
    "input.placeholderForeground": cereals.white.color_hex,
    "inputOption.activeBackground": cereals.magenta.color_hex,
    "inputOption.activeBorder": cereals.magenta.color_hex,
    "inputOption.activeForeground": cereals.background.color_hex,
    "inputOption.hoverBackground": cereals.brightBlack.color_hex,
    "keybindingLabel.background": cereals.black.color_hex,
    "keybindingLabel.border": cereals.brightBlack.color_hex,
    "keybindingLabel.bottomBorder": cereals.brightBlack.color_hex,
    "list.activeSelectionBackground": cereals.brightBlack.color_hex,
    "list.errorForeground": cereals.red.color_hex,
    "list.focusOutline": cereals.brightBlack.color_hex,
    "list.hoverBackground": cereals.black.color_hex,
    "list.inactiveSelectionBackground": cereals.black.color_hex,
    "list.warningForeground": cereals.yellow.color_hex,
    "menu.background": cereals.background.color_hex,
    "menu.border": cereals.brightBlack.color_hex,
    "menu.foreground": cereals.foreground.color_hex,
    "menu.selectionBackground": cereals.black.color_hex,
    "menu.selectionForeground": cereals.foreground.color_hex,
    "menu.separatorBackground": cereals.black.color_hex,
    "menubar.selectionBackground": cereals.brightBlack.color_hex,
    "panel.background": cereals.background.color_hex,
    "panel.border": cereals.black.color_hex,
    "panel.dropBorder": cereals.white.color_hex,
    "panelInput.border": cereals.brightBlack.color_hex,
    "panelSection.border": cereals.brightBlack.color_hex,
    "panelSection.dropBackground": cereals.black.color_hex,
    "panelSectionHeader.background": cereals.background.color_hex,
    "panelSectionHeader.foreground": cereals.white.color_hex,
    "panelTitle.activeBorder": cereals.red.color_hex,
    "panelTitle.activeForeground": cereals.foreground.color_hex,
    "panelTitle.inactiveForeground": cereals.white.color_hex,
    "panelTitleBadge.background": cereals.cyan.color_hex,
    "panelTitleBadge.foreground": cereals.background.color_hex,
    "peekViewEditor.background": cereals.green.color_hex,
    "progressBar.background": cereals.red.color_hex,
    "quickInput.background": cereals.background.color_hex,
    "quickInput.foreground": cereals.foreground.color_hex,
    "quickInputList.focusBackground": cereals.black.color_hex,
    "quickInputList.focusForeground": cereals.foreground.color_hex,
    "quickInputList.focusIconForeground": cereals.foreground.color_hex,
    "scrollbarSlider.activeBackground": cereals.red.color_hex,
    "scrollbarSlider.background": cereals.black.color_hex,
    "scrollbarSlider.hoverBackground": cereals.brightBlack.color_hex,
    "selection.background": cereals.brightBlack.color_hex,
    "settings.dropdownBackground": cereals.black.color_hex,
    "settings.dropdownBorder": cereals.blue.color_hex,
    "settings.dropdownForeground": cereals.foreground.color_hex,
    "sideBar.background": cereals.background.color_hex,
    "sideBar.border": cereals.black.color_hex,
    "sideBar.dropBackground": cereals.black.color_hex,
    "sideBar.foreground": cereals.foreground.color_hex,
    "sideBarSectionHeader.background": cereals.background.color_hex,
    "sideBarSectionHeader.border": cereals.black.color_hex,
    "sideBarSectionHeader.foreground": cereals.foreground.color_hex,
    "sideBarTitle.foreground": cereals.foreground.color_hex,
    "statusBar.background": cereals.background.color_hex,
    "statusBar.border": cereals.background.color_hex,
    "statusBar.debuggingBackground": cereals.green.color_hex,
    "statusBar.debuggingForeground": cereals.background.color_hex,
    "statusBar.focusBorder": cereals.white.color_hex,
    "statusBar.foreground": cereals.foreground.color_hex,
    "statusBar.noFolderBackground": cereals.background.color_hex,
    "statusBarItem.activeBackground": cereals.brightBlack.color_hex,
    "statusBarItem.errorBackground": cereals.red.color_hex,
    "statusBarItem.errorForeground": cereals.black.color_hex,
    "statusBarItem.hoverBackground": cereals.black.color_hex,
    "statusBarItem.hoverForeground": cereals.foreground.color_hex,
    "statusBarItem.prominentBackground": cereals.yellow.color_hex,
    "statusBarItem.prominentForeground": cereals.background.color_hex,
    "statusBarItem.remoteBackground": cereals.blue.color_hex,
    "statusBarItem.remoteForeground": cereals.background.color_hex,
    "tab.activeBackground": cereals.black.color_hex,
    "tab.activeBorder": cereals.black.color_hex,
    "tab.activeBorderTop": cereals.red.color_hex,
    "tab.activeForeground": cereals.foreground.color_hex,
    "tab.activeModifiedBorder": cereals.black.color_hex,
    "tab.border": cereals.brightBlack.color_hex,
    "tab.hoverBackground": cereals.black.color_hex,
    "tab.inactiveBackground": cereals.background.color_hex,
    "tab.inactiveForeground": cereals.white.color_hex,
    "tab.inactiveModifiedBorder": cereals.black.color_hex,
    "tab.unfocusedActiveBorder": cereals.black.color_hex,
    "tab.unfocusedActiveBorderTop": cereals.brightBlack.color_hex,
    "tab.unfocusedActiveModifiedBorder": cereals.black.color_hex,
    "tab.unfocusedHoverBackground": cereals.black.color_hex,
    "tab.unfocusedInactiveModifiedBorder": cereals.black.color_hex,
    "textLink.activeForeground": cereals.brightBlue.color_hex,
    "textLink.foreground": cereals.blue.color_hex,
    "titleBar.activeBackground": cereals.black.color_hex,
    "titleBar.activeForeground": cereals.foreground.color_hex,
    "titleBar.border": cereals.black.color_hex,
    "titleBar.inactiveBackground": cereals.background.color_hex,
    "titleBar.inactiveForeground": cereals.foreground.color_hex,
    "toolbar.activeBackground": cereals.black.color_hex,
    "toolbar.hoverBackground": cereals.black.color_hex,
    "tree.inactiveIndentGuidesStroke": cereals.black.color_hex,
    "tree.indentGuidesStroke": cereals.brightBlack.color_hex,
    "welcomePage.background": cereals.background.color_hex,
    "welcomePage.progress.background": cereals.background.color_hex,
    "welcomePage.progress.foreground": cereals.foreground.color_hex,
    "welcomePage.tileBackground": cereals.black.color_hex,
    "welcomePage.tileBorder": cereals.brightBlack.color_hex,
    "welcomePage.tileHoverBackground": cereals.black.color_hex,
    "widget.border": cereals.brightBlack.color_hex,
  };
}
